CREATE TABLE conversation_participants
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conversation_id      BIGINT                                  NOT NULL,
    user_id              BIGINT                                  NOT NULL,
    role                 VARCHAR(50),
    joined_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    left_at              TIMESTAMP WITHOUT TIME ZONE,
    is_active            BOOLEAN,
    last_read_at         TIMESTAMP WITHOUT TIME ZONE,
    notification_enabled BOOLEAN,
    CONSTRAINT pk_conversation_participants PRIMARY KEY (id)
);

CREATE TABLE conversations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    type            VARCHAR(50)                             NOT NULL,
    course_code     VARCHAR(20),
    description     TEXT,
    avatar_url      VARCHAR(500),
    created_by      BIGINT,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    last_message_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_conversations PRIMARY KEY (id)
);

CREATE TABLE message_attachments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id    BIGINT                                  NOT NULL,
    file_name     VARCHAR(255)                            NOT NULL,
    file_type     VARCHAR(100),
    file_size     BIGINT,
    file_url      VARCHAR(500)                            NOT NULL,
    thumbnail_url VARCHAR(500),
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_message_attachments PRIMARY KEY (id)
);

CREATE TABLE message_reactions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    emoji      VARCHAR(10)                             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_message_reactions PRIMARY KEY (id)
);

CREATE TABLE message_read_status
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    read_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_message_read_status PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conversation_id   BIGINT                                  NOT NULL,
    sender_id         BIGINT                                  NOT NULL,
    content           TEXT                                    NOT NULL,
    message_type      VARCHAR(50),
    parent_message_id BIGINT,
    is_edited         BOOLEAN,
    is_deleted        BOOLEAN,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    neptun_code  VARCHAR(6)                              NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    program      VARCHAR(255),
    faculty      VARCHAR(255),
    semester     INTEGER,
    status       VARCHAR(50),
    avatar_url   VARCHAR(500),
    last_seen_at TIMESTAMP WITHOUT TIME ZONE,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_neptun_code UNIQUE (neptun_code);

ALTER TABLE conversations
    ADD CONSTRAINT FK_CONVERSATIONS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE conversation_participants
    ADD CONSTRAINT FK_CONVERSATION_PARTICIPANTS_ON_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id);

ALTER TABLE conversation_participants
    ADD CONSTRAINT FK_CONVERSATION_PARTICIPANTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_PARENT_MESSAGE FOREIGN KEY (parent_message_id) REFERENCES messages (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

ALTER TABLE message_attachments
    ADD CONSTRAINT FK_MESSAGE_ATTACHMENTS_ON_MESSAGE FOREIGN KEY (message_id) REFERENCES messages (id);

ALTER TABLE message_reactions
    ADD CONSTRAINT FK_MESSAGE_REACTIONS_ON_MESSAGE FOREIGN KEY (message_id) REFERENCES messages (id);

ALTER TABLE message_reactions
    ADD CONSTRAINT FK_MESSAGE_REACTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE message_read_status
    ADD CONSTRAINT FK_MESSAGE_READ_STATUS_ON_MESSAGE FOREIGN KEY (message_id) REFERENCES messages (id);

ALTER TABLE message_read_status
    ADD CONSTRAINT FK_MESSAGE_READ_STATUS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);